/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zubu' at '6/27/16 9:51 AM' with Gradle 2.14
 *
 * @author zubu, @date 6/27/16 9:51 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
